services:
  - type: web
    name: the_efficient_birder # the name of this service, eg hello-world
    env: ruby # this app is written in ruby
    plan: free # make sure to set this to free or you'll get billed $$$
    buildCommand: "./bin/render-build.sh" # # we already created these two files for you
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: the_efficient_birder
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: the_efficient_birder
    databaseName: the_efficient_birder
    user: the_efficient_birder
    plan: free
